### ISSUE TITLE
Heading ain't centered

### ISSUE THREAD

**Issue by sarthaktexas** [hackclub/workshop-deck-playground#1]
![image](https://user-images.githubusercontent.com/28282096/93224053-55eb4c80-f736-11ea-99b0-578c47d1988f.png)
I don't fully understand react and why every other heading is centered, but it's an issue, so I'm putting it here.

**Comment by lachlanjc** [comment]
Yep, this is because the lines are centered horizontally with flexbox, but the text itself isn't. Trade-offs!
